//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedngoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public int TypeID { get; set; }
        public int OrganiserID { get; set; }
        public System.DateTime TaskTime { get; set; }
        public string TaskAddress { get; set; }
        public string TaskName { get; set; }
        public bool Cancelled { get; set; }
    }
}
