//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedngoService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMeeting
    {
        public int MeetingID { get; set; }
        public int ClientID { get; set; }
    }
}
